/*  PROBLEM 002
    <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:</p>
    <p class="center">1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
    <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
*/

#include    <iostream>

#define     MAX 4000000

using namespace std;

int main(){
    int first = 1,
        second = 2,
        sum = 0,
        old;
    
    // Generate the Fibonacci sequence up to the MAX value.
    while(second < MAX){
        // Sum if the Fibonacci value is even-valued.
        if(second % 2 == 0)
            sum += second;
        
        old     = first;
        first   = second;
        second += old;
    }
    cout << "Sum of the even-valued terms in the Fibonacci seqeuence whose values do not exceed " << MAX << ": " << sum << endl;
    
    return 0;
}